const els={pdfInput:document.getElementById('pdfInput'),selectCard:document.getElementById('selectCard'),docTitle:document.getElementById('docTitle'),docPages:document.getElementById('docPages'),recentList:document.getElementById('recentList'),langSelect:document.getElementById('langSelect'),voiceSelect:document.getElementById('voiceSelect'),rate:document.getElementById('rate'),pitch:document.getElementById('pitch'),volume:document.getElementById('volume'),seekBar:document.getElementById('seekBar'),reader:document.getElementById('reader'),exportAudio:document.getElementById('exportAudio'),podcastTitle:document.getElementById('podcastTitle'),savePodcastBtn:document.getElementById('savePodcastBtn'),chaptersList:document.getElementById('chaptersList'),addBookmarkBtn:document.getElementById('addBookmarkBtn'),bookmarksList:document.getElementById('bookmarksList'),darkToggle:document.getElementById('darkToggle'),btnPlayPause:document.getElementById('btnPlayPause'),playerTitle:document.getElementById('playerTitle'),libraryList:document.getElementById('libraryList'),navHome:document.getElementById('navHome'),navLibrary:document.getElementById('navLibrary'),navSettings:document.getElementById('navSettings'),playButton:document.getElementById('playButton'),voiceDrawer:document.getElementById('voiceDrawer'),drawerHandle:document.getElementById('drawerHandle'),nowPlaying:document.getElementById('nowPlaying'),nowPlayingIcon:document.getElementById('nowPlayingIcon'),nowPlayingLabel:document.getElementById('nowPlayingLabel'),playerUi:document.getElementById('playerUi')}
let db,currentDoc=null,currentPages=[],currentPageIndex=0,currentCharIndex=0,isPlaying=false,currentVoice=null,currentScreen='home',playbackTimer=null
function openDB(){return new Promise((res,rej)=>{const req=indexedDB.open('pdfTts',2);req.onupgradeneeded=e=>{const d=req.result;let docs,pods,chapters,marks;try{docs=d.createObjectStore('documents',{keyPath:'id',autoIncrement:true})}catch{}try{pods=d.createObjectStore('podcasts',{keyPath:'id',autoIncrement:true})}catch{}try{chapters=d.createObjectStore('chapters',{keyPath:'id',autoIncrement:true})}catch{}try{marks=d.createObjectStore('bookmarks',{keyPath:'id',autoIncrement:true})}catch{}try{chapters.createIndex('byDocPage',['docId','pageIndex'],{unique:true})}catch{}try{marks.createIndex('byDoc',['documentId'],{unique:false})}catch{}try{docs.createIndex('byLastOpened',['lastOpenedAt'],{unique:false})}catch{}};req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
function tx(store,mode){return db.transaction(store,mode).objectStore(store)}
function put(store,obj){return new Promise((res,rej)=>{const r=tx(store,'readwrite').put(obj);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function getAll(store){return new Promise((res,rej)=>{const r=tx(store,'readonly').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function queryIndex(store,index,key){return new Promise((res,rej)=>{const i=tx(store,'readonly').index(index);const r=i.getAll(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function loadPdfJs(){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='vendor/pdf.min.js';s.onload=()=>resolve(window['pdfjsLib']);s.onerror=()=>{const c=document.createElement('script');c.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';c.onload=()=>resolve(window['pdfjsLib']);c.onerror=reject;document.head.appendChild(c)};document.head.appendChild(s)})}
function setWorkerSrc(){if(window['pdfjsLib']){const w=document.createElement('script');w.src='vendor/pdf.worker.min.js';w.onload=()=>{window['pdfjsLib'].GlobalWorkerOptions.workerSrc='vendor/pdf.worker.min.js'};w.onerror=()=>{window['pdfjsLib'].GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'};document.head.appendChild(w)}}
function initTheme(){const t=localStorage.getItem('theme');const isDark=t==='dark';document.body.classList.toggle('dark',isDark);els.darkToggle.checked=isDark;els.darkToggle.addEventListener('change',()=>{document.body.classList.toggle('dark',els.darkToggle.checked);localStorage.setItem('theme',els.darkToggle.checked?'dark':'light')})}
function populateVoices(){const lang=els.langSelect.value;const voices=speechSynthesis.getVoices().filter(v=>v.lang===lang);els.voiceSelect.innerHTML='';voices.forEach(v=>{const o=document.createElement('option');o.value=v.name;o.text=v.name;els.voiceSelect.appendChild(o)});currentVoice=voices.find(v=>v.default)||voices[0]||null}
function syncSettings(){els.langSelect.addEventListener('change',populateVoices);els.voiceSelect.addEventListener('change',()=>{const name=els.voiceSelect.value;currentVoice=speechSynthesis.getVoices().find(v=>v.name===name)||null})}
function renderRecent(){getAll('documents').then(list=>{list.sort((a,b)=>b.lastOpenedAt-a.lastOpenedAt);els.recentList.innerHTML='';list.forEach(d=>{const li=document.createElement('li');const btn=document.createElement('button');btn.textContent='Open';btn.addEventListener('click',()=>{loadDocumentRecord(d);show('reader')});li.textContent=d.title+' • '+d.pageCount+' pages ';li.appendChild(btn);els.recentList.appendChild(li)})})}
function loadDocumentRecord(rec){currentDoc=rec;els.docTitle.textContent=rec.title;els.docPages.textContent=rec.pageCount;queryIndex('chapters','byDocPage',[rec.id,0]).then(r=>{if(r.length===0){els.chaptersList.innerHTML='';return}return loadChaptersForDoc(rec.id)}).then(()=>{renderBookmarks();isPlaying=false;currentPageIndex=0;currentCharIndex=0;updateReader();updateSeek()})}
function loadChaptersForDoc(docId){return queryIndex('chapters','byDocPage',[docId,0]).then(()=>getAll('chapters')).then(all=>{currentPages=all.filter(x=>x.docId===docId).sort((a,b)=>a.pageIndex-b.pageIndex).map(x=>x.text);renderChapters()})}
function renderChapters(){els.chaptersList.innerHTML='';currentPages.forEach((t,i)=>{const li=document.createElement('li');const b=document.createElement('button');b.textContent='Play Page '+(i+1);b.addEventListener('click',()=>{currentPageIndex=i;currentCharIndex=0;updateReader();show('player');if(els.btnPlayPause)els.btnPlayPause.textContent='Play'});li.textContent='Page '+(i+1)+' ';li.appendChild(b);els.chaptersList.appendChild(li)})}
function renderBookmarks(){if(!currentDoc)return;queryIndex('bookmarks','byDoc',currentDoc.id).then(list=>{els.bookmarksList.innerHTML='';list.sort((a,b)=>b.createdAt-a.createdAt);list.forEach(m=>{const li=document.createElement('li');const b=document.createElement('button');b.textContent='Go';b.addEventListener('click',()=>{currentPageIndex=m.pageIndex;currentCharIndex=m.charIndex;updateReader();updateSeek();show('player');if(els.btnPlayPause)els.btnPlayPause.textContent='Play'});li.textContent='Page '+(m.pageIndex+1)+' • '+m.charIndex+' ';li.appendChild(b);els.bookmarksList.appendChild(li)})})}
function addBookmark(){if(!currentDoc||currentPages.length===0)return;put('bookmarks',{documentId:currentDoc.id,pageIndex:currentPageIndex,charIndex:currentCharIndex,note:null,createdAt:Date.now()}).then(()=>renderBookmarks())}
function updateReader(){const t=currentPages[currentPageIndex]||'';els.reader.textContent=t.slice(Math.max(0,currentCharIndex),Math.min(t.length,currentCharIndex+2000))}
function updateSeek(){const t=currentPages[currentPageIndex]||'';const p=t.length?Math.floor((currentCharIndex/t.length)*100):0;if(els.seekBar)els.seekBar.value=String(p)}
function speakChunk(text){const u=new SpeechSynthesisUtterance(text);u.rate=parseFloat(els.rate.value);u.pitch=parseFloat(els.pitch.value);u.volume=parseFloat(els.volume.value);u.lang=els.langSelect.value;u.voice=currentVoice;u.onend=()=>{if(!isPlaying)return;const pageText=currentPages[currentPageIndex]||'';if(currentCharIndex>=pageText.length){if(currentPageIndex<currentPages.length-1){currentPageIndex++;currentCharIndex=0;updateReader();updateSeek();nextChunk()}else{isPlaying=false}}else{nextChunk()}};u.onboundary=e=>{currentCharIndex+=e.charLength||0;updateSeek()};speechSynthesis.speak(u)}
function nextChunk(){const t=currentPages[currentPageIndex]||'';const size=600;const s=currentCharIndex;const chunk=t.slice(s,Math.min(t.length,s+size));if(chunk.length===0){return}speakChunk(chunk)}
function play(){if(currentPages.length===0)return;isPlaying=true;speechSynthesis.cancel();nextChunk();setMediaSession();if(els.btnPlayPause)els.btnPlayPause.textContent='Pause';if(els.playerUi)els.playerUi.classList.add('active-playing');if(els.nowPlaying){els.nowPlaying.classList.add('playing');els.nowPlaying.classList.remove('paused');els.nowPlaying.style.display='flex'};if(els.nowPlayingIcon)els.nowPlayingIcon.textContent='⏸';if(els.nowPlayingLabel)els.nowPlayingLabel.textContent='Now Playing';if(playbackTimer)clearInterval(playbackTimer);playbackTimer=setInterval(syncPlaybackUI,500)}
function pause(){isPlaying=false;speechSynthesis.cancel();if(els.btnPlayPause)els.btnPlayPause.textContent='Play';if(els.playerUi)els.playerUi.classList.remove('active-playing');if(els.nowPlaying){els.nowPlaying.classList.add('paused');els.nowPlaying.classList.remove('playing');els.nowPlaying.style.display='flex'};if(els.nowPlayingIcon)els.nowPlayingIcon.textContent='▶';if(els.nowPlayingLabel)els.nowPlayingLabel.textContent='Paused';if(playbackTimer){clearInterval(playbackTimer);playbackTimer=null}}
function seekPercent(p){const t=currentPages[currentPageIndex]||'';currentCharIndex=Math.floor((p/100)*t.length);updateReader()}
function setMediaSession(){if(!('mediaSession' in navigator))return;navigator.mediaSession.metadata=new MediaMetadata({title:els.docTitle.textContent,artist:'Text To Speech',album:'PDF'});navigator.mediaSession.setActionHandler('play',()=>play());navigator.mediaSession.setActionHandler('pause',()=>pause());navigator.mediaSession.setActionHandler('seekforward',()=>seekPercent(Math.min(100,parseInt(els.seekBar.value)+5)));navigator.mediaSession.setActionHandler('seekbackward',()=>seekPercent(Math.max(0,parseInt(els.seekBar.value)-5)))}
function syncPlaybackUI(){const speaking=speechSynthesis.speaking;isPlaying=speaking;updateSeek();if(els.btnPlayPause)els.btnPlayPause.textContent=speaking?'Pause':'Play';if(els.playerUi)els.playerUi.classList.toggle('active-playing',speaking);if(els.nowPlaying){els.nowPlaying.style.display='flex';els.nowPlaying.classList.toggle('playing',speaking);els.nowPlaying.classList.toggle('paused',!speaking)};if(els.nowPlayingIcon)els.nowPlayingIcon.textContent=speaking?'⏸':'▶';if(els.nowPlayingLabel)els.nowPlayingLabel.textContent=speaking?'Now Playing':'Paused'}
function savePodcast(){if(!currentDoc)return;put('podcasts',{documentId:currentDoc.id,title:els.podcastTitle.value||currentDoc.title,createdAt:Date.now()})}
function extractWithPdfJs(arrayBuffer,title){return loadPdfJs().then(lib=>{setWorkerSrc();return lib.getDocument({data:arrayBuffer}).promise}).then(doc=>doc.getMetadata().then(()=>doc.numPages).then(async pages=>{const texts=[];for(let i=1;i<=pages;i++){const p=await doc.getPage(i);const c=await p.getTextContent();const t=c.items.map(it=>it.str).join(' ');texts.push(t)}return {pages,pdfDoc:doc,texts}})).then(({pages,texts})=>{els.docTitle.textContent=title;els.docPages.textContent=pages;currentPages=texts;currentPageIndex=0;currentCharIndex=0;renderChapters();updateReader();const rec={title,lastOpenedAt:Date.now(),pageCount:pages};return put('documents',rec).then(id=>{currentDoc={...rec,id};const ops=[];texts.forEach((t,i)=>ops.push(put('chapters',{docId:id,pageIndex:i,text:t})));return Promise.all(ops).then(()=>renderRecent())})})}
function onPdfSelected(file){const r=new FileReader();r.onload=()=>{extractWithPdfJs(r.result,file.name)};r.readAsArrayBuffer(file)}
function show(screen){document.querySelectorAll('.screen').forEach(s=>{s.classList.toggle('active',s.dataset.screen===screen)});currentScreen=screen;syncPlaybackUI()}
function renderLibrary(){getAll('podcasts').then(list=>{list.sort((a,b)=>b.createdAt-a.createdAt);els.libraryList.innerHTML='';list.forEach(p=>{const li=document.createElement('li');const t=document.createElement('div');t.textContent=p.title;const row=document.createElement('div');const btnPlay=document.createElement('button');btnPlay.textContent='Play';btnPlay.addEventListener('click',()=>{show('player');els.playerTitle.textContent=p.title;if(els.podcastTitle)els.podcastTitle.value=p.title;if(els.btnPlayPause)els.btnPlayPause.textContent='Play'});const btnDel=document.createElement('button');btnDel.textContent='Delete';btnDel.addEventListener('click',()=>{const tr=db.transaction('podcasts','readwrite');tr.objectStore('podcasts').delete(p.id).onsuccess=()=>renderLibrary()});row.appendChild(btnPlay);row.appendChild(btnDel);li.appendChild(t);li.appendChild(row);els.libraryList.appendChild(li)})})}
function initUI(){els.pdfInput.addEventListener('change',e=>{const f=e.target.files&&e.target.files[0];if(f)onPdfSelected(f)});if(els.selectCard)els.selectCard.addEventListener('click',()=>els.pdfInput.click());if(els.btnPlayPause)els.btnPlayPause.addEventListener('click',()=>{if(isPlaying)pause();else play()});if(els.seekBar)els.seekBar.addEventListener('input',e=>{seekPercent(parseInt(e.target.value))});if(els.addBookmarkBtn)els.addBookmarkBtn.addEventListener('click',addBookmark);if(els.savePodcastBtn)els.savePodcastBtn.addEventListener('click',()=>{savePodcast();renderLibrary();show('library')});if(els.exportAudio)els.exportAudio.addEventListener('click',()=>{});if(els.navHome)els.navHome.addEventListener('click',()=>{show('home')});if(els.navLibrary)els.navLibrary.addEventListener('click',()=>{renderLibrary();show('library')});if(els.navSettings)els.navSettings.addEventListener('click',()=>{show('settings')});if(els.playButton)els.playButton.addEventListener('click',()=>{show('player');if(els.podcastTitle)els.podcastTitle.value=currentDoc?currentDoc.title:'';els.playerTitle.textContent=els.podcastTitle?els.podcastTitle.value||'PDF Audio':'PDF Audio';if(els.btnPlayPause)els.btnPlayPause.textContent='Play'});if(els.drawerHandle)els.drawerHandle.addEventListener('click',()=>{els.voiceDrawer.classList.toggle('open')});if(els.podcastTitle){els.podcastTitle.addEventListener('input',e=>{const v=e.target.value;els.playerTitle.textContent=v||'PDF Audio'})};if(els.nowPlaying){els.nowPlaying.addEventListener('click',()=>{if(isPlaying)pause();else play()})}}
function boot(){initTheme();openDB().then(r=>{db=r;renderRecent();renderLibrary()});syncSettings();populateVoices();speechSynthesis.onvoiceschanged=populateVoices;initUI();isPlaying=false;if(els.btnPlayPause)els.btnPlayPause.textContent='Play';if(els.nowPlaying){els.nowPlaying.style.display='flex';els.nowPlaying.classList.add('paused');els.nowPlaying.classList.remove('playing')};if(els.nowPlayingIcon)els.nowPlayingIcon.textContent='▶';if(els.nowPlayingLabel)els.nowPlayingLabel.textContent='Paused';if(els.podcastTitle){els.podcastTitle.value=currentDoc?currentDoc.title:'';els.playerTitle.textContent=els.podcastTitle.value||'PDF Audio'};window.addEventListener('focus',syncPlaybackUI);document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncPlaybackUI()})}
boot()
